'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
'
Namespace Security
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SecurityServiceSoap", [Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SecRestric()))>  _
    Partial Public Class SecurityService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private securityHeaderValueField As SecurityHeader
        
        Private SignInOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SignInReadOnlyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SignIn2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private SignOutOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLicenseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetACLsByEntityIdsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateACLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetACLUpdateRestrictionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddSystemACLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetSystemACLsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEntACLsByEntityIdsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.VaultVersion.My.MySettings.Default.VaultVersion_localhost_SecurityService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property SecurityHeaderValue() As SecurityHeader
            Get
                Return Me.securityHeaderValueField
            End Get
            Set
                Me.securityHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SignInCompleted As SignInCompletedEventHandler
        
        '''<remarks/>
        Public Event SignInReadOnlyCompleted As SignInReadOnlyCompletedEventHandler
        
        '''<remarks/>
        Public Event SignIn2Completed As SignIn2CompletedEventHandler
        
        '''<remarks/>
        Public Event SignOutCompleted As SignOutCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLicenseCompleted As GetLicenseCompletedEventHandler
        
        '''<remarks/>
        Public Event GetACLsByEntityIdsCompleted As GetACLsByEntityIdsCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateACLCompleted As UpdateACLCompletedEventHandler
        
        '''<remarks/>
        Public Event GetACLUpdateRestrictionsCompleted As GetACLUpdateRestrictionsCompletedEventHandler
        
        '''<remarks/>
        Public Event AddSystemACLCompleted As AddSystemACLCompletedEventHandler
        
        '''<remarks/>
        Public Event SetSystemACLsCompleted As SetSystemACLsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEntACLsByEntityIdsCompleted As GetEntACLsByEntityIdsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/SignIn", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SignIn(ByVal userName As String, ByVal userPassword As String, ByVal knowledgeVault As String)
            Me.Invoke("SignIn", New Object() {userName, userPassword, knowledgeVault})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignInAsync(ByVal userName As String, ByVal userPassword As String, ByVal knowledgeVault As String)
            Me.SignInAsync(userName, userPassword, knowledgeVault, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignInAsync(ByVal userName As String, ByVal userPassword As String, ByVal knowledgeVault As String, ByVal userState As Object)
            If (Me.SignInOperationCompleted Is Nothing) Then
                Me.SignInOperationCompleted = AddressOf Me.OnSignInOperationCompleted
            End If
            Me.InvokeAsync("SignIn", New Object() {userName, userPassword, knowledgeVault}, Me.SignInOperationCompleted, userState)
        End Sub
        
        Private Sub OnSignInOperationCompleted(ByVal arg As Object)
            If (Not (Me.SignInCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignInCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/SignInReadOnly", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SignInReadOnly(ByVal userName As String, ByVal userPassword As String, ByVal knowledgeVault As String)
            Me.Invoke("SignInReadOnly", New Object() {userName, userPassword, knowledgeVault})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignInReadOnlyAsync(ByVal userName As String, ByVal userPassword As String, ByVal knowledgeVault As String)
            Me.SignInReadOnlyAsync(userName, userPassword, knowledgeVault, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignInReadOnlyAsync(ByVal userName As String, ByVal userPassword As String, ByVal knowledgeVault As String, ByVal userState As Object)
            If (Me.SignInReadOnlyOperationCompleted Is Nothing) Then
                Me.SignInReadOnlyOperationCompleted = AddressOf Me.OnSignInReadOnlyOperationCompleted
            End If
            Me.InvokeAsync("SignInReadOnly", New Object() {userName, userPassword, knowledgeVault}, Me.SignInReadOnlyOperationCompleted, userState)
        End Sub
        
        Private Sub OnSignInReadOnlyOperationCompleted(ByVal arg As Object)
            If (Not (Me.SignInReadOnlyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignInReadOnlyCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/SignIn2", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SignIn2(ByVal userName As String, ByVal userPassword As String)
            Me.Invoke("SignIn2", New Object() {userName, userPassword})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignIn2Async(ByVal userName As String, ByVal userPassword As String)
            Me.SignIn2Async(userName, userPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignIn2Async(ByVal userName As String, ByVal userPassword As String, ByVal userState As Object)
            If (Me.SignIn2OperationCompleted Is Nothing) Then
                Me.SignIn2OperationCompleted = AddressOf Me.OnSignIn2OperationCompleted
            End If
            Me.InvokeAsync("SignIn2", New Object() {userName, userPassword}, Me.SignIn2OperationCompleted, userState)
        End Sub
        
        Private Sub OnSignIn2OperationCompleted(ByVal arg As Object)
            If (Not (Me.SignIn2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignIn2Completed(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/SignOut", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SignOut()
            Me.Invoke("SignOut", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignOutAsync()
            Me.SignOutAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignOutAsync(ByVal userState As Object)
            If (Me.SignOutOperationCompleted Is Nothing) Then
                Me.SignOutOperationCompleted = AddressOf Me.OnSignOutOperationCompleted
            End If
            Me.InvokeAsync("SignOut", New Object(-1) {}, Me.SignOutOperationCompleted, userState)
        End Sub
        
        Private Sub OnSignOutOperationCompleted(ByVal arg As Object)
            If (Not (Me.SignOutCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignOutCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/GetLicense", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLicense() As License
            Dim results() As Object = Me.Invoke("GetLicense", New Object(-1) {})
            Return CType(results(0),License)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLicenseAsync()
            Me.GetLicenseAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLicenseAsync(ByVal userState As Object)
            If (Me.GetLicenseOperationCompleted Is Nothing) Then
                Me.GetLicenseOperationCompleted = AddressOf Me.OnGetLicenseOperationCompleted
            End If
            Me.InvokeAsync("GetLicense", New Object(-1) {}, Me.GetLicenseOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLicenseOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLicenseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLicenseCompleted(Me, New GetLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/GetACLsByEntityIds", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetACLsByEntityIds(ByVal entityIds() As Long) As ACL()
            Dim results() As Object = Me.Invoke("GetACLsByEntityIds", New Object() {entityIds})
            Return CType(results(0),ACL())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetACLsByEntityIdsAsync(ByVal entityIds() As Long)
            Me.GetACLsByEntityIdsAsync(entityIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetACLsByEntityIdsAsync(ByVal entityIds() As Long, ByVal userState As Object)
            If (Me.GetACLsByEntityIdsOperationCompleted Is Nothing) Then
                Me.GetACLsByEntityIdsOperationCompleted = AddressOf Me.OnGetACLsByEntityIdsOperationCompleted
            End If
            Me.InvokeAsync("GetACLsByEntityIds", New Object() {entityIds}, Me.GetACLsByEntityIdsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetACLsByEntityIdsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetACLsByEntityIdsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetACLsByEntityIdsCompleted(Me, New GetACLsByEntityIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/UpdateACL", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateACL(ByVal entityId As Long, ByVal entries() As ACE, ByVal prpgType As PrpgType) As ACL
            Dim results() As Object = Me.Invoke("UpdateACL", New Object() {entityId, entries, prpgType})
            Return CType(results(0),ACL)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateACLAsync(ByVal entityId As Long, ByVal entries() As ACE, ByVal prpgType As PrpgType)
            Me.UpdateACLAsync(entityId, entries, prpgType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateACLAsync(ByVal entityId As Long, ByVal entries() As ACE, ByVal prpgType As PrpgType, ByVal userState As Object)
            If (Me.UpdateACLOperationCompleted Is Nothing) Then
                Me.UpdateACLOperationCompleted = AddressOf Me.OnUpdateACLOperationCompleted
            End If
            Me.InvokeAsync("UpdateACL", New Object() {entityId, entries, prpgType}, Me.UpdateACLOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateACLOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateACLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateACLCompleted(Me, New UpdateACLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/GetACLUpdateRestrictions", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetACLUpdateRestrictions(ByVal entityId As Long, ByVal entries() As ACE) As SecRestric()
            Dim results() As Object = Me.Invoke("GetACLUpdateRestrictions", New Object() {entityId, entries})
            Return CType(results(0),SecRestric())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetACLUpdateRestrictionsAsync(ByVal entityId As Long, ByVal entries() As ACE)
            Me.GetACLUpdateRestrictionsAsync(entityId, entries, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetACLUpdateRestrictionsAsync(ByVal entityId As Long, ByVal entries() As ACE, ByVal userState As Object)
            If (Me.GetACLUpdateRestrictionsOperationCompleted Is Nothing) Then
                Me.GetACLUpdateRestrictionsOperationCompleted = AddressOf Me.OnGetACLUpdateRestrictionsOperationCompleted
            End If
            Me.InvokeAsync("GetACLUpdateRestrictions", New Object() {entityId, entries}, Me.GetACLUpdateRestrictionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetACLUpdateRestrictionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetACLUpdateRestrictionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetACLUpdateRestrictionsCompleted(Me, New GetACLUpdateRestrictionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/AddSystemACL", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddSystemACL(ByVal entries() As ACE) As ACL
            Dim results() As Object = Me.Invoke("AddSystemACL", New Object() {entries})
            Return CType(results(0),ACL)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddSystemACLAsync(ByVal entries() As ACE)
            Me.AddSystemACLAsync(entries, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddSystemACLAsync(ByVal entries() As ACE, ByVal userState As Object)
            If (Me.AddSystemACLOperationCompleted Is Nothing) Then
                Me.AddSystemACLOperationCompleted = AddressOf Me.OnAddSystemACLOperationCompleted
            End If
            Me.InvokeAsync("AddSystemACL", New Object() {entries}, Me.AddSystemACLOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddSystemACLOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddSystemACLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddSystemACLCompleted(Me, New AddSystemACLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/SetSystemACLs", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SetSystemACLs(ByVal entityIds() As Long, ByVal aclId As Long)
            Me.Invoke("SetSystemACLs", New Object() {entityIds, aclId})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetSystemACLsAsync(ByVal entityIds() As Long, ByVal aclId As Long)
            Me.SetSystemACLsAsync(entityIds, aclId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetSystemACLsAsync(ByVal entityIds() As Long, ByVal aclId As Long, ByVal userState As Object)
            If (Me.SetSystemACLsOperationCompleted Is Nothing) Then
                Me.SetSystemACLsOperationCompleted = AddressOf Me.OnSetSystemACLsOperationCompleted
            End If
            Me.InvokeAsync("SetSystemACLs", New Object() {entityIds, aclId}, Me.SetSystemACLsOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetSystemACLsOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetSystemACLsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetSystemACLsCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AutodeskDM/Services/Security/1/26/2009/GetEntACLsByEntityIds", RequestNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", ResponseNamespace:="http://AutodeskDM/Services/Security/1/26/2009/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEntACLsByEntityIds(ByVal entityIds() As Long) As EntsAndACLs
            Dim results() As Object = Me.Invoke("GetEntACLsByEntityIds", New Object() {entityIds})
            Return CType(results(0),EntsAndACLs)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEntACLsByEntityIdsAsync(ByVal entityIds() As Long)
            Me.GetEntACLsByEntityIdsAsync(entityIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEntACLsByEntityIdsAsync(ByVal entityIds() As Long, ByVal userState As Object)
            If (Me.GetEntACLsByEntityIdsOperationCompleted Is Nothing) Then
                Me.GetEntACLsByEntityIdsOperationCompleted = AddressOf Me.OnGetEntACLsByEntityIdsOperationCompleted
            End If
            Me.InvokeAsync("GetEntACLsByEntityIds", New Object() {entityIds}, Me.GetEntACLsByEntityIdsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEntACLsByEntityIdsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEntACLsByEntityIdsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEntACLsByEntityIdsCompleted(Me, New GetEntACLsByEntityIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/", IsNullable:=false)>  _
    Partial Public Class SecurityHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private ticketField As String
        
        Private userIdField As Long
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Ticket() As String
            Get
                Return Me.ticketField
            End Get
            Set
                Me.ticketField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As Long
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class EntACL
        
        Private entIdField As Long
        
        Private aCLIdField As Long
        
        Private sysACLIdField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property EntId() As Long
            Get
                Return Me.entIdField
            End Get
            Set
                Me.entIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ACLId() As Long
            Get
                Return Me.aCLIdField
            End Get
            Set
                Me.aCLIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property SysACLId() As Long
            Get
                Return Me.sysACLIdField
            End Get
            Set
                Me.sysACLIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class EntsAndACLs
        
        Private aCLArrayField() As ACL
        
        Private entACLArrayField() As EntACL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ACLArray")>  _
        Public Property ACLArray() As ACL()
            Get
                Return Me.aCLArrayField
            End Get
            Set
                Me.aCLArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("EntACLArray")>  _
        Public Property EntACLArray() As EntACL()
            Get
                Return Me.entACLArrayField
            End Get
            Set
                Me.entACLArrayField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class ACL
        
        Private aCEArrayField() As ACE
        
        Private idField As Long
        
        '''<remarks/>
        Public Property ACEArray() As ACE()
            Get
                Return Me.aCEArrayField
            End Get
            Set
                Me.aCEArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class ACE
        
        Private permisArrayField() As AccessPermis
        
        Private userGrpIdField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Permis")>  _
        Public Property PermisArray() As AccessPermis()
            Get
                Return Me.permisArrayField
            End Get
            Set
                Me.permisArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UserGrpId() As Long
            Get
                Return Me.userGrpIdField
            End Get
            Set
                Me.userGrpIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class AccessPermis
        
        Private idField As Long
        
        Private valField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Val() As Boolean
            Get
                Return Me.valField
            End Get
            Set
                Me.valField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class SecRestric
        
        Private paramArrayField() As Object
        
        Private codeField As SecRestricCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ParamArray")>  _
        Public Property [ParamArray]() As Object()
            Get
                Return Me.paramArrayField
            End Get
            Set
                Me.paramArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Code() As SecRestricCode
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Public Enum SecRestricCode
        
        '''<remarks/>
        LessRestrctiveParent
        
        '''<remarks/>
        BadEntityId
        
        '''<remarks/>
        UnsupportedEntityClass
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Partial Public Class License
        
        Private nameField As String
        
        Private typField As LicenseType
        
        Private bhvField As LicenseBehavior
        
        Private idField As String
        
        Private serverField As String
        
        Private hostField As String
        
        Private serialNumField As String
        
        Private expireDateField As Date
        
        Private expireDateFieldSpecified As Boolean
        
        Private usageTypField As LicenseUsage
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Typ() As LicenseType
            Get
                Return Me.typField
            End Get
            Set
                Me.typField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Bhv() As LicenseBehavior
            Get
                Return Me.bhvField
            End Get
            Set
                Me.bhvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Server() As String
            Get
                Return Me.serverField
            End Get
            Set
                Me.serverField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Host() As String
            Get
                Return Me.hostField
            End Get
            Set
                Me.hostField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property SerialNum() As String
            Get
                Return Me.serialNumField
            End Get
            Set
                Me.serialNumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ExpireDate() As Date
            Get
                Return Me.expireDateField
            End Get
            Set
                Me.expireDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ExpireDateSpecified() As Boolean
            Get
                Return Me.expireDateFieldSpecified
            End Get
            Set
                Me.expireDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UsageTyp() As LicenseUsage
            Get
                Return Me.usageTypField
            End Get
            Set
                Me.usageTypField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Public Enum LicenseType
        
        '''<remarks/>
        Unknown
        
        '''<remarks/>
        Network
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Public Enum LicenseBehavior
        
        '''<remarks/>
        Unknown
        
        '''<remarks/>
        Permanent
        
        '''<remarks/>
        TermExtendable
        
        '''<remarks/>
        TermNonExtendable
        
        '''<remarks/>
        Trial
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Public Enum LicenseUsage
        
        '''<remarks/>
        Unknown
        
        '''<remarks/>
        Commercial
        
        '''<remarks/>
        Edu
        
        '''<remarks/>
        Emr
        
        '''<remarks/>
        Nfr
        
        '''<remarks/>
        Trial
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://AutodeskDM/Services/Security/1/26/2009/")>  _
    Public Enum PrpgType
        
        '''<remarks/>
        None
        
        '''<remarks/>
        AppendPermissions
        
        '''<remarks/>
        ReplacePermissions
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub SignInCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub SignInReadOnlyCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub SignIn2CompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub SignOutCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub GetLicenseCompletedEventHandler(ByVal sender As Object, ByVal e As GetLicenseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLicenseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As License
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),License)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub GetACLsByEntityIdsCompletedEventHandler(ByVal sender As Object, ByVal e As GetACLsByEntityIdsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetACLsByEntityIdsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ACL()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ACL())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub UpdateACLCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateACLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateACLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ACL
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ACL)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub GetACLUpdateRestrictionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetACLUpdateRestrictionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetACLUpdateRestrictionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SecRestric()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SecRestric())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub AddSystemACLCompletedEventHandler(ByVal sender As Object, ByVal e As AddSystemACLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddSystemACLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ACL
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ACL)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub SetSystemACLsCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub GetEntACLsByEntityIdsCompletedEventHandler(ByVal sender As Object, ByVal e As GetEntACLsByEntityIdsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEntACLsByEntityIdsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EntsAndACLs
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EntsAndACLs)
            End Get
        End Property
    End Class
End Namespace
